### ISSUE TITLE
choice conflict warning "if-else" in grammar 

### ISSUE THREAD

**Issue by JonathanMurray** [gj-kth/compilatrocious#5]
Warning: Choice conflict in [...] construct at line 297, column 12.
   [javacc]          Expansion nested within construct and expansion following construct
   [javacc]          have common prefixes, one of which is: "else"
   [javacc]          Consider using a lookahead of 2 or more for nested expansion.

**Comment by glindstedt** [comment]
warning gone after fix, close?
